"""Initial Migration

Revision ID: 165539a683a0
Revises: e4b6f06d6e45
Create Date: 2019-10-02 11:32:30.554481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165539a683a0'
down_revision = 'e4b6f06d6e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('authors', sa.Column('author_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_authors_author_name'), 'authors', ['author_name'], unique=False)
    op.drop_index('ix_authors_authorname', table_name='authors')
    op.drop_column('authors', 'authorname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('authorname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_authors_authorname', 'authors', ['authorname'], unique=False)
    op.drop_index(op.f('ix_authors_author_name'), table_name='authors')
    op.drop_column('authors', 'author_name')
    op.drop_table('comments')
    op.drop_table('books')
    # ### end Alembic commands ###
