"""Initial Migration

Revision ID: 1e394296ab6d
Revises: f64a4f2750a7
Create Date: 2019-10-04 08:43:31.424378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e394296ab6d'
down_revision = 'f64a4f2750a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image', sa.String(), nullable=True))
    op.add_column('books', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('books', 'book_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'title')
    op.drop_column('books', 'image')
    # ### end Alembic commands ###
