"""Initial Migration

Revision ID: 90b9daf5699d
Revises: 165539a683a0
Create Date: 2019-10-02 11:46:44.486322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b9daf5699d'
down_revision = '165539a683a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('authors', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'pass_secure')
    op.drop_column('admin', 'pass_secure')
    # ### end Alembic commands ###
